import Head from "next/head";
import { HotdogCard } from "../components/hotdogCard";
import React from "react";
import styles from "../styles/Home.module.css";
import Search from "../components/search";
import AdminHotdogShop from "../components/hotdogShops";
import HotdogShops from "../components/hotdogShops";
import Map from "../components/Map";

export default function Home({ data }) {
  console.log("Index-home", data);

  return (
    <div>
      <Head>
        <title>Hotdog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Search />
      <HotdogCard data={data} />
      <AdminHotdogShop />
      <HotdogShops />
      <main className={styles.main}>
        <Map />
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const { hotdog_shops } = await import("/data/data.json");
  return {
    props: {
      data: hotdog_shops,
    },
  };
}
