import Head from "next/head";
import { HotdogCard } from "../components/hotdogCard";
import React from "react";
import styles from "../styles/Home.module.css";
import Search from "../components/search";

// import dynamic from "next/dynamic";

// import dynamic from "next/dynamic";
//Når jeg henter inn map kommer window feilen og hvis jeg tar bort map så kommer det undefined data
// import Map from "../components/Map/map";
import Map from "../components/Map";

// const ClientComponent = dynamic(() => import("../components/ClientComponent"), {
//   // Do not import in server side
//   ssr: false,
// });

export default function Home({ data }) {
  console.log("Index-home", data);
  // useEffect(() => {
  //   window.welcomeMessage = "Welcome to CodingDeft!";
  // }, []);
  // if (typeof window !== "undefined") {
  //   window.welcomeMessage = "Welcome to CodingDeft!";
  // }

  return (
    <div>
      <Head>
        <title>Hotdog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Search />
      <HotdogCard data={data} />
      {/* <ClientComponent /> */}
      <main className={styles.main}>
        <Map />
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const { hotdog_shops } = await import("/data/data.json");
  return {
    props: {
      data: hotdog_shops,
    },
  };
}
